version: "3.9"
services:
  minecraft:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "chan-mai/Docker-Minecraft-PaperMC-Server:latest"
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "8G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/opt/minecraft:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
