services:
  minecraft:
    image: docker.io/marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "mcserver"
    environment:
      PAPERMC_FLAGS: "--nojline"
      # Uncomment to set memory size explicitly
      # MEMORYSIZE: "1G"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - "/home/pi/mcserver:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
